#!/usr/bin/env bash
#
# Regenerate the whole favicon set, in both brand colours, from one SVG.
#
# This exists because the set drifted: favicon.svg was recoloured three times
# while the PNG and ICO fallbacks kept the value they were rasterised with in
# August, so browsers that fall back to PNG were still showing the original
# violet long after the site had gone green. A hand-run pipeline that has to be
# remembered is a pipeline that will be forgotten.
#
#   ./scripts/gen-favicons.sh
#
# rsvg-convert, not ImageMagick: ImageMagick's built-in SVG renderer flattens
# this artwork to a white square. `brew install librsvg` if it is missing.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
PUB=public
BRAND=brand
SRC=$BRAND/favicon.svg

command -v rsvg-convert >/dev/null || { echo "需要 rsvg-convert：brew install librsvg"; exit 1; }
command -v magick >/dev/null || { echo "需要 ImageMagick"; exit 1; }

GREEN="#90FF3A"
VIOLET="#8E47FF"

# The sizes index.html actually references, plus the PWA and Apple ones the
# manifest points at. Nothing here is speculative — a size no document asks for
# is a file nobody fetches.
# Exactly the sizes something asks for: index.html links 32/48/96/192,
# site.webmanifest lists 192/256/384/512, and apple-touch-icon.png is the one
# unsized file Safari looks for. 64 and 128 were generated for a while and
# referenced by nothing; the per-device Apple sizes likewise — iOS has scaled
# the single 180 down since iOS 8.
PNG_SIZES=(32 48 96 192 256 384 512)

render() {          # render <svg> <size> <out>
  rsvg-convert -w "$2" -h "$2" -o "$3" "$1"
}

build_set() {       # build_set <svg> <suffix> [sizes...]
  local svg=$1 sfx=$2; shift 2
  local sizes=("$@"); [[ ${#sizes[@]} -eq 0 ]] && sizes=("${PNG_SIZES[@]}")
  for s in "${sizes[@]}"; do
    render "$svg" "$s" "$PUB/favicon$sfx-${s}x${s}.png"
  done
  render "$svg" 180 "$PUB/apple-touch-icon$sfx.png"
  # The ICO carries the small sizes only; the large ones would quadruple the
  # file for tabs that never render above 32.
  magick "$PUB/favicon$sfx-16x16.png" "$PUB/favicon$sfx-32x32.png" \
         "$PUB/favicon$sfx-48x48.png" "$PUB/favicon$sfx.ico" 2>/dev/null \
    || magick "$PUB/favicon$sfx-32x32.png" "$PUB/favicon$sfx-48x48.png" "$PUB/favicon$sfx.ico"
}

# favicon.svg is both the source everything else is rendered from *and* a
# published asset — index.html links it directly, and every modern browser
# prefers it over the PNGs. It lives in brand/ with the other source art and is
# copied out, so there is one file to recolour rather than two that can drift.
cp "$SRC" "$PUB/favicon.svg"

# The maskable icon, which site.webmanifest lists under purpose:maskable.
#
# This used to be generated by hand and then never again: favicon.svg was
# recoloured three times while maskable-*.png kept the violet it was rasterised
# with, so the PWA install icon was a different colour from the site for weeks.
# Anything rendered from brand art belongs in this script for exactly that
# reason.
for s in 192 512; do
  render "$BRAND/logo-maskable.svg" "$s" "$PUB/maskable-${s}x${s}.png"
done

# 16 is not in PNG_SIZES (no <link> asks for it) but the ICO wants it.
render "$SRC" 16 "$PUB/favicon-16x16.png"

echo "绿色（默认）"
build_set "$SRC" ""

# Violet only needs the sizes the runtime rewrite can reach — index.html links
# 32/48/96/192, the .ico and apple-touch. site.webmanifest asks for
# 256/384/512, but it is static JSON and never switches brand, so violet copies
# of those would be files nothing can ever request.
VIOLET_SIZES=(32 48 96 192)

echo "紫色"
VSVG=$(mktemp -t favicon-violet).svg
sed "s/$GREEN/$VIOLET/gI" "$SRC" > "$VSVG"
cp "$VSVG" "$PUB/favicon-violet.svg"
render "$PUB/favicon-violet.svg" 16 "$PUB/favicon-violet-16x16.png"
build_set "$PUB/favicon-violet.svg" "-violet" "${VIOLET_SIZES[@]}"
rm -f "$VSVG" "$PUB/favicon-16x16.png" "$PUB/favicon-violet-16x16.png"

echo
# Check the SVGs, not the rasters. The mark is a coloured glyph on
# transparency: flattening it to sample a pixel mixes the fill with whatever
# background the flatten used, and reports that instead. The SVG fill is the
# actual source of truth, and the PNGs are rendered from it in the same run.
# Stamp the hrefs with a hash of the source art.
#
# Cloudflare caches these for four hours and this project has no purge
# credentials configured, so a recolour otherwise keeps serving the old icon to
# anyone who has visited before — which is exactly what happened: the .ico went
# green on disk and browsers kept showing the August violet for hours.
#
# A content hash makes a recoloured file a different URL, which no cache
# anywhere can confuse with the old one. Derived from favicon.svg because every
# other file in the set is rendered from it.
HASH=$(md5 -q "$SRC" | cut -c1-8)
perl -0pi -e "s{(href=\"/(?:favicon|apple-touch-icon)[^\"?]*)(\?v=[a-f0-9]+)?\"}{\$1?v=$HASH\"}g" index.html
echo "  版本戳 ?v=$HASH 已写入 index.html"
echo

echo "核对"
for f in "$SRC" "$PUB/favicon-violet.svg"; do
  printf "  %-30s %s\n" "$(basename "$f")" "$(grep -oE '#[0-9A-Fa-f]{6}' "$f" | sort -u | tr '\n' ' ')"
done
printf "  %-30s %s\n" "生成的 PNG/ICO" "$(ls "$PUB" | grep -cE '^(favicon|apple-touch-icon)' ) 个"
