import type {
  AdminImage,
  AdminQuotaTx,
  AdminUser,
  AIGeneration,
  AIStatus,
  ApiToken,
  CheckinRecord,
  CheckinResult,
  Dashboard,
  Image,
  Passkey,
  ProfileInput,
  PublicStats,
  QuotaInfo,
  QuotaTransaction,
  Report,
  OAuthStatus,
  StorageProfile,
  User,
  UserGroup,
} from "./types";
import { currentBrand } from "./BrandContext";
import { currentLang } from "./LangContext";
import { dicts } from "./i18n";

const BASE = "";

async function jfetch<T>(path: string, opts: RequestInit = {}): Promise<T> {
  // FormData must set its own Content-Type: the multipart boundary is
  // generated by the browser, and forcing application/json here makes the
  // server parse the body as JSON and reject every file upload.
  const isForm = opts.body instanceof FormData;
  // Accept-Language on every call, so a rejection comes back in the language
  // the page is already in. Without it an English UI shows Chinese errors,
  // which reads worse than an untranslated interface — the error is exactly
  // the moment the reader needs to understand.
  const lang = currentLang() === "zh" ? "zh-CN" : "en";
  // The brand hint lets the server render emails (OTP codes) in the theme the
  // person is actually looking at. It is a hint, not state: the server clamps
  // unknown values and defaults to green.
  const brand = currentBrand();
  const r = await fetch(BASE + path, {
    credentials: "include",
    headers: isForm
      ? { "Accept-Language": lang, "X-Openimg-Brand": brand, ...(opts.headers || {}) }
      : { "Content-Type": "application/json", "Accept-Language": lang, "X-Openimg-Brand": brand, ...(opts.headers || {}) },
    ...opts,
  });
  if (!r.ok) {
    let msg = `${r.status} ${r.statusText}`;
    try {
      const body = await r.json();
      if (body?.error) msg = body.error;
    } catch {}
    throw new Error(msg);
  }
  if (r.status === 204) return undefined as T;
  return r.json();
}

// ----- Auth -----
export const authApi = {
  /** Mails a signup code. Says plainly when the address is already taken —
   *  signup cannot hide that, and pretending otherwise sends the user off to
   *  wait for a code that was never going to work. */
  registerCode: (email: string) =>
    jfetch<{ sent: true; ttl_secs: number; resend_in: number }>("/auth/register/code", {
      method: "POST",
      body: JSON.stringify({ email }),
    }),
  register: (email: string, password: string, code: string, name?: string, ref?: string) =>
    jfetch<User>("/auth/register", {
      method: "POST",
      body: JSON.stringify({ email, password, code, name, ref }),
    }),
  login: (email: string, password: string) =>
    jfetch<User>("/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }),
  logout: () => jfetch<{ ok: boolean }>("/auth/logout", { method: "POST" }),
  me: () => jfetch<User>("/auth/me"),
  providers: () => jfetch<{ providers: string[] }>("/auth/providers").then((r) => r.providers),
  requestOtp: (email: string) =>
    jfetch<{ sent: boolean; ttl_secs: number; resend_in: number }>("/auth/email/request-otp", {
      method: "POST",
      body: JSON.stringify({ email }),
    }),
  verifyOtp: (email: string, code: string, name?: string, ref?: string) =>
    jfetch<User>("/auth/email/verify", { method: "POST", body: JSON.stringify({ email, code, name, ref }) }),
  /** picbi 只解绑,不登录:它没有 /auth/picbi/start,也不在 providers 列表里。 */
  unlinkOAuth: (provider: "google" | "github" | "picbi") =>
    jfetch<{ ok: boolean }>(`/auth/${provider}/unlink`, { method: "POST" }),

  passkeyList: () =>
    jfetch<{ passkeys: Passkey[] | null }>("/auth/passkey/list").then((r) => r.passkeys ?? []),
  passkeyDelete: (id: string) => jfetch<{ ok: true }>(`/auth/passkey/${id}`, { method: "DELETE" }),
  /** Requires an emailed code: a passkey is a permanent second key to the
   *  account, so enrolment is gated the same way a password change is. */
  passkeyEnrollBegin: (code: string) =>
    jfetch<{ flow: string; options: { publicKey: any } }>("/auth/passkey/enroll/begin", {
      method: "POST",
      body: JSON.stringify({ code }),
    }),
  passkeyEnrollFinish: (flow: string, name: string, credential: any) =>
    jfetch<{ id: string; name: string }>("/auth/passkey/enroll/finish", {
      method: "POST",
      body: JSON.stringify({ flow, name, credential }),
    }),
  passkeyLoginBegin: (email?: string) =>
    jfetch<{ flow: string; options: { publicKey: any }; discoverable?: boolean }>("/auth/passkey/login/begin", {
      method: "POST",
      body: JSON.stringify({ email: email || "" }),
    }),
  passkeyLoginFinish: (email: string, flow: string, credential: any) =>
    jfetch<User>("/auth/passkey/login/finish", {
      method: "POST",
      body: JSON.stringify({ email, flow, credential }),
    }),
};

// ----- User preferences -----
export const userApi = {
  updatePreferences: (prefs: Record<string, unknown>) =>
    jfetch<{ ok: true }>("/api/preferences", { method: "PATCH", body: JSON.stringify(prefs) }),
  /** 把浏览器时区报上去。
   *
   *  签到的「一天」从几点开始要按用户实际过的那一天算,而服务端没别的办法
   *  知道那是哪个时区。报一次存在账号上,不跟着每次请求走——跟着请求走的话
   *  改一下就能让「今天」变成另一天,签到可以刷。
   *
   *  失败不提示也不重试:没报上去只是退回 UTC 日界,也就是这个字段存在之前
   *  的行为,为它弹个错只会让人困惑。 */
  reportTimezone: () => {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (!tz) return Promise.resolve();
    return jfetch<{ ok: true }>("/api/preferences", {
      method: "PATCH",
      body: JSON.stringify({ timezone: tz }),
    }).catch(() => undefined);
  },
  deleteAccount: (confirm: string) =>
    jfetch<{ ok: true; deleted_images: number }>("/api/account", {
      method: "DELETE",
      body: JSON.stringify({ confirm }),
    }),
};

// ----- Images -----
/**
 * 上传的返回。promoted 只在这一次上传恰好触发了升级或扩容时出现——服务端顺带
 * 判的,平时不下发这个字段。
 */
export interface UploadResult {
  image: Image;
  deduplicated: boolean;
  promoted?: { group: string; granted_bytes: number; loyalty: boolean };
}

export const imageApi = {
  publicStats: () => jfetch<PublicStats>("/api/public-stats"),

  /**
   * Uploads one file. Progress is reported through XHR rather than fetch
   * because fetch still has no upload-progress event, and a picture host
   * without a progress bar feels broken on anything slower than a LAN.
   */
  /**
   * 按网址取图。**服务端下载**,不是浏览器下载。
   *
   * 浏览器这条路走不通:第三方图片地址基本都会被 CORS 挡掉,而能绕过 CORS 的
   * 只有服务端。代价是这个接口让任何登录用户都能驱使我们的服务器去请求一个
   * 地址,防护全在后端的 fetchurl 包里。
   *
   * 没有进度:字节从来没有经过浏览器,进度只有服务端知道。与其编一个假的百分
   * 比,不如在界面上就显示成"正在取"。
   */
  uploadFromURL(url: string): Promise<UploadResult> {
    return jfetch("/api/upload/from-url", {
      method: "POST",
      body: JSON.stringify({ url }),
    });
  },

  upload(
    file: File,
    opts: { onProgress?: (pct: number) => void; signal?: AbortSignal } = {},
  ): Promise<UploadResult> {
    return new Promise((resolve, reject) => {
      const form = new FormData();
      form.append("file", file);

      const xhr = new XMLHttpRequest();
      xhr.open("POST", BASE + "/api/upload");
      // The fetch wrapper above is not on this path: uploads go through XHR
      // for byte-level progress, so the header has to be set again here. This
      // is where "file too large" and "format not allowed" come back.
      xhr.setRequestHeader("Accept-Language", currentLang() === "zh" ? "zh-CN" : "en");
      xhr.setRequestHeader("X-Openimg-Brand", currentBrand());
      xhr.withCredentials = true;

      xhr.upload.onprogress = (e) => {
        if (e.lengthComputable && opts.onProgress) {
          opts.onProgress(Math.round((e.loaded / e.total) * 100));
        }
      };
      xhr.onload = () => {
        let body: any = null;
        try {
          body = JSON.parse(xhr.responseText);
        } catch {}
        if (xhr.status >= 200 && xhr.status < 300) resolve(body);
        else reject(new Error(body?.error || `${xhr.status} ${xhr.statusText}`));
      };
      xhr.onerror = () => reject(new Error(dicts[currentLang()].upload.networkError));
      xhr.onabort = () => reject(new Error(dicts[currentLang()].common.cancelled));
      opts.signal?.addEventListener("abort", () => xhr.abort());

      xhr.send(form);
    });
  },

  list: (params: { limit?: number; offset?: number; q?: string; sort?: SortKey } = {}) => {
    const qs = new URLSearchParams();
    if (params.limit) qs.set("limit", String(params.limit));
    if (params.offset) qs.set("offset", String(params.offset));
    if (params.q) qs.set("q", params.q);
    if (params.sort) qs.set("sort", params.sort);
    return jfetch<{ images: Image[] | null; total: number; limit: number; offset: number }>(
      "/api/images?" + qs.toString(),
    ).then((r) => ({ ...r, images: r.images ?? [] }));
  },
  remove: (id: string) => jfetch<{ ok: true }>(`/api/images/${id}`, { method: "DELETE" }),
  /**
   * Deletes many at once. `all: true` takes everything matching `q` rather
   * than the listed ids; the server caps each call, so keep calling while
   * `remaining` is above zero.
   */
  bulkRemove: (body: { ids?: string[]; all?: boolean; q?: string; code?: string }) =>
    jfetch<{ ok: true; deleted: number; remaining: number }>("/api/images/bulk-delete", {
      method: "POST",
      body: JSON.stringify(body),
    }),
  /** Renders one display size on demand. Idempotent — asking twice is free. */
  makeVariant: (id: string, width: 200 | 600 | 1200) =>
    jfetch<{ ok: true; variant: string; url: string; existing?: boolean; bytes?: number }>(
      `/api/images/${id}/variant`,
      { method: "POST", body: JSON.stringify({ width }) },
    ),
};

// ----- AI image generation -----
/**
 * Text to image. Three calls, and the middle one does not wait for a picture:
 * generation takes tens of seconds, so `generate` returns as soon as the task
 * is accepted and `generations` is polled until that record turns terminal.
 *
 * The completed record carries an `image_id` into the `images` map, whose
 * entries are the same `Image` objects the gallery lists — a generated picture
 * is an ordinary upload from the moment it lands.
 */
export const aiApi = {
  /** `{enabled: false}` on a deployment with no upstream key configured. */
  status: () => jfetch<AIStatus>("/api/ai/status"),
  generate: (prompt: string, size: string, resolution: string) =>
    jfetch<{ generation: AIGeneration }>("/api/ai/generate", {
      method: "POST",
      body: JSON.stringify({ prompt, size, resolution }),
    }).then((r) => r.generation),
  /**
   * Retouching: the same submission, given one to four pictures to work from.
   *
   * The ids are the user's own images and the server resolves them to their
   * public CDN URLs before calling upstream — nothing is uploaded again, and
   * nothing is base64'd, because the files are already on a public origin the
   * model can fetch for itself.
   *
   * `size` and `resolution` are genuinely optional here: omit the size and the
   * output keeps the shape of the picture that went in, which is what someone
   * removing a watermark almost always wants.
   */
  edit: (prompt: string, imageIds: string[], size?: string | null, resolution?: string | null) =>
    jfetch<{ generation: AIGeneration }>("/api/ai/edit", {
      method: "POST",
      body: JSON.stringify({
        prompt,
        image_ids: imageIds,
        ...(size ? { size } : {}),
        ...(resolution ? { resolution } : {}),
      }),
    }).then((r) => r.generation),
  /** Newest first, capped server-side. Both members can come back null.
   *  Carries generations and edits alike; the pages filter by `kind`. */
  /** 从列表里删掉一条记录。alsoImage 时连产出图一起删。
   *  服务端只是把它标成隐藏——行是日限的计数单位,真删等于退回当天配额。 */
  deleteGeneration: (id: string, alsoImage: boolean) =>
    jfetch<{ ok: true; image_deleted: boolean }>(
      `/api/ai/generations/${id}${alsoImage ? "?image=1" : ""}`,
      { method: "DELETE" },
    ),
  generations: () =>
    jfetch<{ generations: AIGeneration[] | null; images: Record<string, Image> | null }>(
      "/api/ai/generations",
    ).then((r) => ({ generations: r.generations ?? [], images: r.images ?? {} })),
};

// ----- Quota & check-in -----
export const quotaApi = {
  info: () => jfetch<QuotaInfo>("/api/quota"),
  /** Aggregated in the database across every live image — not a sample. */
  storageSummary: () =>
    jfetch<{
      images: number;
      size_orig: number; size_stored: number;
      size_primary: number; size_variants: number; size_thumbs: number; size_unclassified: number;
      by_profile: { id: string; name: string; kind: string; bytes: number; images: number }[];
      by_format: { ext: string; bytes: number; images: number }[];
    }>("/api/storage/summary"),
  transactions: (limit = 20, offset = 0) =>
    jfetch<{ transactions: QuotaTransaction[] | null; total: number; limit: number; offset: number }>(
      `/api/quota/transactions?limit=${limit}&offset=${offset}`,
    ).then((r) => ({ ...r, transactions: r.transactions ?? [] })),
  checkin: () => jfetch<CheckinResult>("/api/checkin", { method: "POST" }),
  checkinHistory: (limit = 60) =>
    jfetch<{ records: CheckinRecord[] | null }>(`/api/checkin/history?limit=${limit}`).then(
      (r) => r.records ?? [],
    ),
};

// ----- Storage profiles (bring your own bucket) -----
export const storageApi = {
  list: () =>
    jfetch<{ profiles: StorageProfile[] | null }>("/api/storage/profiles").then((r) => r.profiles ?? []),
  create: (cfg: ProfileInput) =>
    jfetch<StorageProfile | { ok: boolean; tested: boolean }>("/api/storage/profiles", {
      method: "POST",
      body: JSON.stringify(cfg),
    }),
  update: (id: string, cfg: Partial<ProfileInput>) =>
    jfetch<StorageProfile | { ok: boolean; tested: boolean }>(`/api/storage/profiles/${id}`, {
      method: "PATCH",
      body: JSON.stringify(cfg),
    }),
  remove: (id: string) => jfetch<{ ok: true }>(`/api/storage/profiles/${id}`, { method: "DELETE" }),
  test: (id: string) => jfetch<{ ok: boolean; error?: string }>(`/api/storage/profiles/${id}/test`, { method: "POST" }),
  setDefault: (id: string) => jfetch<{ ok: true }>(`/api/storage/profiles/${id}/default`, { method: "POST" }),
};

// ----- API tokens -----
export const tokenApi = {
  list: () => jfetch<{ tokens: ApiToken[] | null }>("/api/tokens").then((r) => r.tokens ?? []),
  create: (name: string, expiresInDays = 0) =>
    jfetch<{ token: ApiToken; plain: string; warning: string }>("/api/tokens", {
      method: "POST",
      body: JSON.stringify({ name, expires_in_days: expiresInDays }),
    }),
  remove: (id: string) => jfetch<{ ok: true }>(`/api/tokens/${id}`, { method: "DELETE" }),
};

// ----- Referral -----
export const referralApi = {
  me: () =>
    jfetch<{ code: string; count: number; total_bytes: number; bonus_bytes: number }>("/api/referral/me"),
  list: () =>
    jfetch<{ invitees: { name: string; email: string; created_at: string }[] | null }>(
      "/api/referral/list",
    ).then((r) => r.invitees ?? []),
};

// ----- Admin -----
/** Purposes the server will mail a confirmation code for. */
export type OtpPurpose = "password" | "passkey" | "purge";

export const accountApi = {
  /** Mails a code to the account's own address. The address is never sent by
   *  the client — the server reads it off the session. */
  requestOtp: (purpose: OtpPurpose) =>
    jfetch<{ sent: true; email: string; purpose: OtpPurpose; ttl_secs: number; resend_in: number }>(
      "/api/account/otp",
      { method: "POST", body: JSON.stringify({ purpose }) },
    ),
  uploadAvatar: (file: File) => {
    const form = new FormData();
    form.append("file", file);
    return jfetch<{ ok: true; avatar_url: string }>("/api/account/avatar", { method: "POST", body: form });
  },
  removeAvatar: () => jfetch<{ ok: true }>("/api/account/avatar", { method: "DELETE" }),
  setNickname: (name: string) =>
    jfetch<{ ok: true; name: string }>("/api/account/profile", {
      method: "PATCH",
      body: JSON.stringify({ name }),
    }),
  changePassword: (newPassword: string, code: string) =>
    jfetch<{ ok: true }>("/api/account/password", {
      method: "POST",
      body: JSON.stringify({ new_password: newPassword, code }),
    }),
};

/** Password recovery. Mints no session on request — only on confirm. */
export const resetApi = {
  request: (email: string) =>
    jfetch<{ sent: true; ttl_secs: number; resend_in: number }>("/auth/password/reset/request", {
      method: "POST",
      body: JSON.stringify({ email }),
    }),
  confirm: (email: string, code: string, newPassword: string) =>
    jfetch<{ ok: true; email: string }>("/auth/password/reset", {
      method: "POST",
      body: JSON.stringify({ email, code, new_password: newPassword }),
    }),
};

/** Abuse reports. Anonymous submissions are accepted — requiring an account
 *  to report is a good way to never hear about a problem until your host does. */
export const reportApi = {
  submit: (imageId: string, category: string, reason?: string, contact?: string) =>
    jfetch<{ ok: true }>("/api/report", {
      method: "POST",
      body: JSON.stringify({ image_id: imageId, category, reason: reason || undefined, contact: contact || undefined }),
    }),
};

export interface SharePayload {
  code: string;
  orig_name: string;
  mime: string;
  ext: string;
  width: number;
  height: number;
  size: number;
  views: number;
  created_at: string;
  uploader: string;
  url: string;
  short_url: string;
  thumb_url: string;
  markdown: string;
  html: string;
  html_link: string;
  html_direct: string;
  bbcode: string;
  bbcode_link: string;
  reactions: Record<string, number>;
  mine?: string;
}

/** The public share page behind a short link. No auth required. */
export const shareApi = {
  get: (code: string) => jfetch<SharePayload>(`/api/s/${encodeURIComponent(code)}`),
  react: (code: string, kind: string) =>
    jfetch<SharePayload>(`/api/s/${encodeURIComponent(code)}/react`, {
      method: "POST",
      body: JSON.stringify({ kind }),
    }),
  /** Reports by code: the share page never receives the internal image id. */
  report: (code: string, category: string, reason?: string, contact?: string) =>
    jfetch<{ ok: true; message: string }>(`/api/s/${encodeURIComponent(code)}/report`, {
      method: "POST",
      body: JSON.stringify({ category, reason: reason || undefined, contact: contact || undefined }),
    }),
};

/** Report categories. Keys are stable; labels are what both the reporter and
 *  the admin see, so a report never reads differently on the two ends. */
export const REPORT_CATEGORIES = [
  { key: "porn", label: "涉黄内容" },
  { key: "copyright", label: "侵犯版权" },
  { key: "violence", label: "涉恐或血腥" },
  { key: "privacy", label: "个人隐私" },
  { key: "fraud", label: "诈骗或恶意链接" },
  { key: "other", label: "其他违规" },
] as const;

export function reportCategoryLabel(key?: string): string {
  return REPORT_CATEGORIES.find((c) => c.key === key)?.label ?? "其他违规";
}

export const adminApi = {
  dashboard: () => jfetch<Dashboard>("/admin/api/dashboard"),
  listImages: (filters: { status?: string; user_id?: string; limit?: number } = {}) => {
    const qs = new URLSearchParams(filters as Record<string, string>);
    return jfetch<{ images: AdminImage[] | null }>("/admin/api/images?" + qs.toString()).then((r) => r.images ?? []);
  },
  listUsers: () => jfetch<{ users: AdminUser[] | null }>("/admin/api/users").then((r) => r.users ?? []),
  updateUser: (id: string, patch: Partial<{ role: string; status: string; group_id: string; name: string }>) =>
    jfetch<{ ok: true }>("/admin/api/users/" + id, { method: "PATCH", body: JSON.stringify(patch) }),
  banUser: (id: string, purgeImages: boolean, reason?: string) =>
    jfetch<{ ok: true; purged: number }>(`/admin/api/users/${id}/ban`, {
      method: "POST",
      body: JSON.stringify({ purge_images: purgeImages, reason }),
    }),
  listGroups: () => jfetch<{ groups: UserGroup[] | null }>("/admin/api/groups").then((r) => r.groups ?? []),
  updateGroup: (id: string, patch: Partial<UserGroup>) =>
    jfetch<UserGroup>("/admin/api/groups/" + id, { method: "PATCH", body: JSON.stringify(patch) }),
  listTransactions: (opts: { limit?: number; offset?: number; q?: string } = {}) => {
    const p = new URLSearchParams();
    if (opts.limit != null) p.set("limit", String(opts.limit));
    if (opts.offset) p.set("offset", String(opts.offset));
    if (opts.q) p.set("q", opts.q);
    return jfetch<{ transactions: AdminQuotaTx[] | null; total: number }>(
      `/admin/api/quota/transactions?${p}`,
    ).then((r) => ({ transactions: r.transactions ?? [], total: r.total }));
  },
  adjustQuota: (userId: string, bytes: number, reason?: string) =>
    jfetch<{ quota_bytes: number }>("/admin/api/quota/adjust", {
      method: "POST",
      body: JSON.stringify({ user_id: userId, bytes, reason }),
    }),
  listReports: (status?: string) =>
    jfetch<{ reports: Report[] | null }>("/admin/api/reports" + (status ? `?status=${status}` : "")).then(
      (r) => r.reports ?? [],
    ),
  resolveReport: (id: string, action: "dismiss" | "block" | "block_and_ban", note?: string) =>
    jfetch<{ ok: true }>(`/admin/api/reports/${id}/resolve`, {
      method: "POST",
      body: JSON.stringify({ action, note }),
    }),
  blockImage: (id: string) =>
    jfetch<{ ok: true; status: string }>(`/admin/api/images/${id}/block`, { method: "POST" }),
  uploadSettings: () => jfetch<{ keep_original: boolean }>("/admin/api/upload-settings"),
  saveUploadSettings: (v: { keep_original: boolean }) =>
    jfetch<{ keep_original: boolean }>("/admin/api/upload-settings", {
      method: "POST",
      body: JSON.stringify(v),
    }),
  platformStorage: () =>
    jfetch<{
      configured: boolean; bucket: string; endpoint: string; key_prefix: string;
      public_base_url: string; site_base_url: string; sample_url: string; image_count: number;
    }>("/admin/api/storage/platform"),
  savePlatformStorage: (publicBaseUrl: string) =>
    jfetch<{ ok: true; public_base_url: string; affected: number }>("/admin/api/storage/platform", {
      method: "PATCH",
      body: JSON.stringify({ public_base_url: publicBaseUrl }),
    }),
  oauthStatus: () => jfetch<OAuthStatus>("/admin/api/oauth"),
  oauthSave: (provider: "google" | "github", clientId: string, clientSecret: string) =>
    jfetch<{ ok: true; enabled: boolean }>("/admin/api/oauth", {
      method: "POST",
      body: JSON.stringify({ provider, client_id: clientId, client_secret: clientSecret }),
    }),
};

/** Gallery sort orders. Mirrors the whitelist in the backend's image handler —
 * an unknown value there falls back to newest rather than erroring. */
/** Hands a signed-in session back to a native client. See backend
 *  internal/api/native_auth.go for why the code, and not the session, travels. */
export const nativeAuth = {
  code: () => jfetch<{ code: string }>("/auth/native/code", { method: "POST" }),
};

export const SORTS = [
  // Keys and icons only. The labels live in the dictionary: they change with
  // the language, and this module is the API client, not the view.
  { key: "newest", icon: "arrow-down-wide-short" },
  { key: "oldest", icon: "arrow-up-wide-short" },
  { key: "largest", icon: "weight-hanging" },
  { key: "smallest", icon: "feather" },
  { key: "widest", icon: "expand" },
  { key: "name", icon: "arrow-down-a-z" },
] as const;

export type SortKey = (typeof SORTS)[number]["key"];

/** Formats a byte count for display. Used everywhere space is shown. */
export function formatBytes(n: number, digits = 1): string {
  if (!n || n < 0) return "0 B";
  if (n < 1024) return `${n} B`;
  const units = ["KB", "MB", "GB", "TB", "PB"];
  let v = n / 1024;
  let i = 0;
  while (v >= 1024 && i < units.length - 1) {
    v /= 1024;
    i++;
  }
  return `${v.toFixed(digits)} ${units[i]}`;
}
