import type {
  AdminQuotaTx,
  AdminUser,
  ApiToken,
  CheckinRecord,
  CheckinResult,
  Dashboard,
  Image,
  Passkey,
  ProfileInput,
  PublicStats,
  QuotaInfo,
  QuotaTransaction,
  Report,
  OAuthStatus,
  Stats,
  StorageProfile,
  User,
  UserGroup,
} from "./types";

const BASE = "";

async function jfetch<T>(path: string, opts: RequestInit = {}): Promise<T> {
  // FormData must set its own Content-Type: the multipart boundary is
  // generated by the browser, and forcing application/json here makes the
  // server parse the body as JSON and reject every file upload.
  const isForm = opts.body instanceof FormData;
  const r = await fetch(BASE + path, {
    credentials: "include",
    headers: isForm
      ? { ...(opts.headers || {}) }
      : { "Content-Type": "application/json", ...(opts.headers || {}) },
    ...opts,
  });
  if (!r.ok) {
    let msg = `${r.status} ${r.statusText}`;
    try {
      const body = await r.json();
      if (body?.error) msg = body.error;
    } catch {}
    throw new Error(msg);
  }
  if (r.status === 204) return undefined as T;
  return r.json();
}

// ----- Auth -----
export const authApi = {
  /** Mails a signup code. Says plainly when the address is already taken —
   *  signup cannot hide that, and pretending otherwise sends the user off to
   *  wait for a code that was never going to work. */
  registerCode: (email: string) =>
    jfetch<{ sent: true; ttl_secs: number; resend_in: number }>("/auth/register/code", {
      method: "POST",
      body: JSON.stringify({ email }),
    }),
  register: (email: string, password: string, code: string, name?: string, ref?: string) =>
    jfetch<User>("/auth/register", {
      method: "POST",
      body: JSON.stringify({ email, password, code, name, ref }),
    }),
  login: (email: string, password: string) =>
    jfetch<User>("/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }),
  logout: () => jfetch<{ ok: boolean }>("/auth/logout", { method: "POST" }),
  me: () => jfetch<User>("/auth/me"),
  providers: () => jfetch<{ providers: string[] }>("/auth/providers").then((r) => r.providers),
  requestOtp: (email: string) =>
    jfetch<{ sent: boolean; ttl_secs: number; resend_in: number }>("/auth/email/request-otp", {
      method: "POST",
      body: JSON.stringify({ email }),
    }),
  verifyOtp: (email: string, code: string, name?: string, ref?: string) =>
    jfetch<User>("/auth/email/verify", { method: "POST", body: JSON.stringify({ email, code, name, ref }) }),
  unlinkOAuth: (provider: "google" | "github") =>
    jfetch<{ ok: boolean }>(`/auth/${provider}/unlink`, { method: "POST" }),

  passkeyList: () =>
    jfetch<{ passkeys: Passkey[] | null }>("/auth/passkey/list").then((r) => r.passkeys ?? []),
  passkeyDelete: (id: string) => jfetch<{ ok: true }>(`/auth/passkey/${id}`, { method: "DELETE" }),
  /** Requires an emailed code: a passkey is a permanent second key to the
   *  account, so enrolment is gated the same way a password change is. */
  passkeyEnrollBegin: (code: string) =>
    jfetch<{ flow: string; options: { publicKey: any } }>("/auth/passkey/enroll/begin", {
      method: "POST",
      body: JSON.stringify({ code }),
    }),
  passkeyEnrollFinish: (flow: string, name: string, credential: any) =>
    jfetch<{ id: string; name: string }>("/auth/passkey/enroll/finish", {
      method: "POST",
      body: JSON.stringify({ flow, name, credential }),
    }),
  passkeyLoginBegin: (email?: string) =>
    jfetch<{ flow: string; options: { publicKey: any }; discoverable?: boolean }>("/auth/passkey/login/begin", {
      method: "POST",
      body: JSON.stringify({ email: email || "" }),
    }),
  passkeyLoginFinish: (email: string, flow: string, credential: any) =>
    jfetch<User>("/auth/passkey/login/finish", {
      method: "POST",
      body: JSON.stringify({ email, flow, credential }),
    }),
};

// ----- User preferences -----
export const userApi = {
  updatePreferences: (prefs: Record<string, unknown>) =>
    jfetch<{ ok: true }>("/api/preferences", { method: "PATCH", body: JSON.stringify(prefs) }),
  deleteAccount: (confirm: string) =>
    jfetch<{ ok: true; deleted_images: number }>("/api/account", {
      method: "DELETE",
      body: JSON.stringify({ confirm }),
    }),
};

// ----- Images -----
export const imageApi = {
  publicStats: () => jfetch<PublicStats>("/api/public-stats"),

  /**
   * Uploads one file. Progress is reported through XHR rather than fetch
   * because fetch still has no upload-progress event, and a picture host
   * without a progress bar feels broken on anything slower than a LAN.
   */
  upload(
    file: File,
    opts: { onProgress?: (pct: number) => void; signal?: AbortSignal } = {},
  ): Promise<{ image: Image; deduplicated: boolean }> {
    return new Promise((resolve, reject) => {
      const form = new FormData();
      form.append("file", file);

      const xhr = new XMLHttpRequest();
      xhr.open("POST", BASE + "/api/upload");
      xhr.withCredentials = true;

      xhr.upload.onprogress = (e) => {
        if (e.lengthComputable && opts.onProgress) {
          opts.onProgress(Math.round((e.loaded / e.total) * 100));
        }
      };
      xhr.onload = () => {
        let body: any = null;
        try {
          body = JSON.parse(xhr.responseText);
        } catch {}
        if (xhr.status >= 200 && xhr.status < 300) resolve(body);
        else reject(new Error(body?.error || `${xhr.status} ${xhr.statusText}`));
      };
      xhr.onerror = () => reject(new Error("网络错误，上传失败"));
      xhr.onabort = () => reject(new Error("已取消"));
      opts.signal?.addEventListener("abort", () => xhr.abort());

      xhr.send(form);
    });
  },

  list: (params: { limit?: number; offset?: number; q?: string; sort?: SortKey } = {}) => {
    const qs = new URLSearchParams();
    if (params.limit) qs.set("limit", String(params.limit));
    if (params.offset) qs.set("offset", String(params.offset));
    if (params.q) qs.set("q", params.q);
    if (params.sort) qs.set("sort", params.sort);
    return jfetch<{ images: Image[] | null; total: number; limit: number; offset: number }>(
      "/api/images?" + qs.toString(),
    ).then((r) => ({ ...r, images: r.images ?? [] }));
  },
  get: (id: string) => jfetch<Image>(`/api/images/${id}`),
  remove: (id: string) => jfetch<{ ok: true }>(`/api/images/${id}`, { method: "DELETE" }),
  /**
   * Deletes many at once. `all: true` takes everything matching `q` rather
   * than the listed ids; the server caps each call, so keep calling while
   * `remaining` is above zero.
   */
  bulkRemove: (body: { ids?: string[]; all?: boolean; q?: string; code?: string }) =>
    jfetch<{ ok: true; deleted: number; remaining: number }>("/api/images/bulk-delete", {
      method: "POST",
      body: JSON.stringify(body),
    }),
  /** Renders one display size on demand. Idempotent — asking twice is free. */
  makeVariant: (id: string, width: 200 | 600 | 1200) =>
    jfetch<{ ok: true; variant: string; url: string; existing?: boolean; bytes?: number }>(
      `/api/images/${id}/variant`,
      { method: "POST", body: JSON.stringify({ width }) },
    ),
  report: (imageId: string, reason: string, contact?: string) =>
    jfetch<{ ok: true; message: string }>("/api/report", {
      method: "POST",
      body: JSON.stringify({ image_id: imageId, reason, contact }),
    }),
};

// ----- Quota & check-in -----
export const quotaApi = {
  info: () => jfetch<QuotaInfo>("/api/quota"),
  /** Aggregated in the database across every live image — not a sample. */
  storageSummary: () =>
    jfetch<{
      images: number;
      size_orig: number; size_stored: number;
      size_primary: number; size_variants: number; size_thumbs: number; size_unclassified: number;
      by_profile: { id: string; name: string; kind: string; bytes: number; images: number }[];
      by_format: { ext: string; bytes: number; images: number }[];
    }>("/api/storage/summary"),
  transactions: (limit = 20, offset = 0) =>
    jfetch<{ transactions: QuotaTransaction[] | null; total: number; limit: number; offset: number }>(
      `/api/quota/transactions?limit=${limit}&offset=${offset}`,
    ).then((r) => ({ ...r, transactions: r.transactions ?? [] })),
  checkin: () => jfetch<CheckinResult>("/api/checkin", { method: "POST" }),
  checkinHistory: (limit = 60) =>
    jfetch<{ records: CheckinRecord[] | null }>(`/api/checkin/history?limit=${limit}`).then(
      (r) => r.records ?? [],
    ),
};

// ----- Storage profiles (bring your own bucket) -----
export const storageApi = {
  list: () =>
    jfetch<{ profiles: StorageProfile[] | null }>("/api/storage/profiles").then((r) => r.profiles ?? []),
  create: (cfg: ProfileInput) =>
    jfetch<StorageProfile | { ok: boolean; tested: boolean }>("/api/storage/profiles", {
      method: "POST",
      body: JSON.stringify(cfg),
    }),
  update: (id: string, cfg: Partial<ProfileInput>) =>
    jfetch<StorageProfile | { ok: boolean; tested: boolean }>(`/api/storage/profiles/${id}`, {
      method: "PATCH",
      body: JSON.stringify(cfg),
    }),
  remove: (id: string) => jfetch<{ ok: true }>(`/api/storage/profiles/${id}`, { method: "DELETE" }),
  test: (id: string) => jfetch<{ ok: boolean; error?: string }>(`/api/storage/profiles/${id}/test`, { method: "POST" }),
  setDefault: (id: string) => jfetch<{ ok: true }>(`/api/storage/profiles/${id}/default`, { method: "POST" }),
  setBackup: (id: string, backupOfId: string) =>
    jfetch<{ ok: true }>(`/api/storage/profiles/${id}/backup`, {
      method: "POST",
      body: JSON.stringify({ backup_of_id: backupOfId }),
    }),
};

// ----- API tokens -----
export const tokenApi = {
  list: () => jfetch<{ tokens: ApiToken[] | null }>("/api/tokens").then((r) => r.tokens ?? []),
  create: (name: string, expiresInDays = 0) =>
    jfetch<{ token: ApiToken; plain: string; warning: string }>("/api/tokens", {
      method: "POST",
      body: JSON.stringify({ name, expires_in_days: expiresInDays }),
    }),
  remove: (id: string) => jfetch<{ ok: true }>(`/api/tokens/${id}`, { method: "DELETE" }),
};

// ----- Referral -----
export const referralApi = {
  me: () =>
    jfetch<{ code: string; count: number; total_bytes: number; bonus_bytes: number }>("/api/referral/me"),
  list: () =>
    jfetch<{ invitees: { name: string; email: string; created_at: string }[] | null }>(
      "/api/referral/list",
    ).then((r) => r.invitees ?? []),
  lookup: (code: string) =>
    jfetch<{ valid: boolean; referrer_name?: string; bonus_bytes?: number }>(
      "/api/referral/lookup?code=" + encodeURIComponent(code),
    ),
};

// ----- Admin -----
/** Purposes the server will mail a confirmation code for. */
export type OtpPurpose = "password" | "passkey" | "purge";

export const accountApi = {
  /** Mails a code to the account's own address. The address is never sent by
   *  the client — the server reads it off the session. */
  requestOtp: (purpose: OtpPurpose) =>
    jfetch<{ sent: true; email: string; purpose: OtpPurpose; ttl_secs: number; resend_in: number }>(
      "/api/account/otp",
      { method: "POST", body: JSON.stringify({ purpose }) },
    ),
  uploadAvatar: (file: File) => {
    const form = new FormData();
    form.append("file", file);
    return jfetch<{ ok: true; avatar_url: string }>("/api/account/avatar", { method: "POST", body: form });
  },
  removeAvatar: () => jfetch<{ ok: true }>("/api/account/avatar", { method: "DELETE" }),
  setNickname: (name: string) =>
    jfetch<{ ok: true; name: string }>("/api/account/profile", {
      method: "PATCH",
      body: JSON.stringify({ name }),
    }),
  changePassword: (newPassword: string, code: string) =>
    jfetch<{ ok: true }>("/api/account/password", {
      method: "POST",
      body: JSON.stringify({ new_password: newPassword, code }),
    }),
};

/** Password recovery. Mints no session on request — only on confirm. */
export const resetApi = {
  request: (email: string) =>
    jfetch<{ sent: true; ttl_secs: number; resend_in: number }>("/auth/password/reset/request", {
      method: "POST",
      body: JSON.stringify({ email }),
    }),
  confirm: (email: string, code: string, newPassword: string) =>
    jfetch<{ ok: true; email: string }>("/auth/password/reset", {
      method: "POST",
      body: JSON.stringify({ email, code, new_password: newPassword }),
    }),
};

/** Abuse reports. Anonymous submissions are accepted — requiring an account
 *  to report is a good way to never hear about a problem until your host does. */
export const reportApi = {
  submit: (imageId: string, category: string, reason?: string, contact?: string) =>
    jfetch<{ ok: true }>("/api/report", {
      method: "POST",
      body: JSON.stringify({ image_id: imageId, category, reason: reason || undefined, contact: contact || undefined }),
    }),
};

export interface SharePayload {
  code: string;
  orig_name: string;
  mime: string;
  ext: string;
  width: number;
  height: number;
  size: number;
  views: number;
  created_at: string;
  uploader: string;
  url: string;
  short_url: string;
  thumb_url: string;
  markdown: string;
  html: string;
  html_link: string;
  html_direct: string;
  bbcode: string;
  bbcode_link: string;
  reactions: Record<string, number>;
  mine?: string;
}

/** The public share page behind a short link. No auth required. */
export const shareApi = {
  get: (code: string) => jfetch<SharePayload>(`/api/s/${encodeURIComponent(code)}`),
  react: (code: string, kind: string) =>
    jfetch<SharePayload>(`/api/s/${encodeURIComponent(code)}/react`, {
      method: "POST",
      body: JSON.stringify({ kind }),
    }),
  /** Reports by code: the share page never receives the internal image id. */
  report: (code: string, category: string, reason?: string, contact?: string) =>
    jfetch<{ ok: true; message: string }>(`/api/s/${encodeURIComponent(code)}/report`, {
      method: "POST",
      body: JSON.stringify({ category, reason: reason || undefined, contact: contact || undefined }),
    }),
};

/** Report categories. Keys are stable; labels are what both the reporter and
 *  the admin see, so a report never reads differently on the two ends. */
export const REPORT_CATEGORIES = [
  { key: "porn", label: "涉黄内容" },
  { key: "copyright", label: "侵犯版权" },
  { key: "violence", label: "涉恐或血腥" },
  { key: "privacy", label: "个人隐私" },
  { key: "fraud", label: "诈骗或恶意链接" },
  { key: "other", label: "其他违规" },
] as const;

export function reportCategoryLabel(key?: string): string {
  return REPORT_CATEGORIES.find((c) => c.key === key)?.label ?? "其他违规";
}

export const adminApi = {
  stats: () => jfetch<Stats>("/admin/api/stats"),
  dashboard: () => jfetch<Dashboard>("/admin/api/dashboard"),
  listImages: (filters: { status?: string; user_id?: string; limit?: number } = {}) => {
    const qs = new URLSearchParams(filters as Record<string, string>);
    return jfetch<{ images: Image[] | null }>("/admin/api/images?" + qs.toString()).then((r) => r.images ?? []);
  },
  listUsers: () => jfetch<{ users: AdminUser[] | null }>("/admin/api/users").then((r) => r.users ?? []),
  updateUser: (id: string, patch: Partial<{ role: string; status: string; group_id: string; name: string }>) =>
    jfetch<{ ok: true }>("/admin/api/users/" + id, { method: "PATCH", body: JSON.stringify(patch) }),
  banUser: (id: string, purgeImages: boolean, reason?: string) =>
    jfetch<{ ok: true; purged: number }>(`/admin/api/users/${id}/ban`, {
      method: "POST",
      body: JSON.stringify({ purge_images: purgeImages, reason }),
    }),
  reconcileUser: (id: string) =>
    jfetch<{ ok: true; delta: number }>(`/admin/api/users/${id}/reconcile`, { method: "POST" }),
  listGroups: () => jfetch<{ groups: UserGroup[] | null }>("/admin/api/groups").then((r) => r.groups ?? []),
  updateGroup: (id: string, patch: Partial<UserGroup>) =>
    jfetch<UserGroup>("/admin/api/groups/" + id, { method: "PATCH", body: JSON.stringify(patch) }),
  listTransactions: (limit = 100) =>
    jfetch<{ transactions: AdminQuotaTx[] | null }>(`/admin/api/quota/transactions?limit=${limit}`).then(
      (r) => r.transactions ?? [],
    ),
  adjustQuota: (userId: string, bytes: number, reason?: string) =>
    jfetch<{ quota_bytes: number }>("/admin/api/quota/adjust", {
      method: "POST",
      body: JSON.stringify({ user_id: userId, bytes, reason }),
    }),
  listReports: (status?: string) =>
    jfetch<{ reports: Report[] | null }>("/admin/api/reports" + (status ? `?status=${status}` : "")).then(
      (r) => r.reports ?? [],
    ),
  resolveReport: (id: string, action: "dismiss" | "block" | "block_and_ban", note?: string) =>
    jfetch<{ ok: true }>(`/admin/api/reports/${id}/resolve`, {
      method: "POST",
      body: JSON.stringify({ action, note }),
    }),
  blockImage: (id: string) =>
    jfetch<{ ok: true; status: string }>(`/admin/api/images/${id}/block`, { method: "POST" }),
  uploadSettings: () => jfetch<{ keep_original: boolean }>("/admin/api/upload-settings"),
  saveUploadSettings: (v: { keep_original: boolean }) =>
    jfetch<{ keep_original: boolean }>("/admin/api/upload-settings", {
      method: "POST",
      body: JSON.stringify(v),
    }),
  platformStorage: () =>
    jfetch<{
      configured: boolean; bucket: string; endpoint: string; key_prefix: string;
      public_base_url: string; site_base_url: string; sample_url: string; image_count: number;
    }>("/admin/api/storage/platform"),
  savePlatformStorage: (publicBaseUrl: string) =>
    jfetch<{ ok: true; public_base_url: string; affected: number }>("/admin/api/storage/platform", {
      method: "PATCH",
      body: JSON.stringify({ public_base_url: publicBaseUrl }),
    }),
  oauthStatus: () => jfetch<OAuthStatus>("/admin/api/oauth"),
  oauthSave: (provider: "google" | "github", clientId: string, clientSecret: string) =>
    jfetch<{ ok: true; enabled: boolean }>("/admin/api/oauth", {
      method: "POST",
      body: JSON.stringify({ provider, client_id: clientId, client_secret: clientSecret }),
    }),
};

/** Gallery sort orders. Mirrors the whitelist in the backend's image handler —
 * an unknown value there falls back to newest rather than erroring. */
export const SORTS = [
  { key: "newest", label: "最新上传", icon: "fa-arrow-down-wide-short" },
  { key: "oldest", label: "最早上传", icon: "fa-arrow-up-wide-short" },
  { key: "largest", label: "占用最大", icon: "fa-weight-hanging" },
  { key: "smallest", label: "占用最小", icon: "fa-feather" },
  { key: "widest", label: "分辨率最高", icon: "fa-expand" },
  { key: "name", label: "文件名", icon: "fa-arrow-down-a-z" },
] as const;

export type SortKey = (typeof SORTS)[number]["key"];

/** Formats a byte count for display. Used everywhere space is shown. */
export function formatBytes(n: number, digits = 1): string {
  if (!n || n < 0) return "0 B";
  if (n < 1024) return `${n} B`;
  const units = ["KB", "MB", "GB", "TB", "PB"];
  let v = n / 1024;
  let i = 0;
  while (v >= 1024 && i < units.length - 1) {
    v /= 1024;
    i++;
  }
  return `${v.toFixed(digits)} ${units[i]}`;
}
