import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

/**
 * Which brand hue the page is painted in.
 *
 * This replaced a ThemeContext that also carried light/dark. The light theme is
 * gone — the product is dark-only — and what is left is one axis, so the module
 * is named after it rather than keeping a "theme" that no longer themes
 * anything.
 *
 * The colours themselves live in CSS: index.css defines the green on :root and
 * the violet under [data-brand="violet"], so switching is one attribute write
 * rather than a re-render of anything that draws colour.
 *
 * The initial value is applied by an inline script in index.html, before React
 * mounts — doing it here instead would paint green first and then flip.
 */
export type Brand = "green" | "violet";

/**
 * Repoint every icon link at the current brand's file.
 *
 * Favicons are files, so unlike everything else on the page they cannot follow
 * a CSS variable — the only lever is the href. Two full sets are generated by
 * scripts/gen-favicons.sh; the violet ones carry a `-violet` infix before the
 * size suffix, so the rewrite is a single substitution either way.
 *
 * Exported because index.html has to run the same logic inline, before React
 * mounts, or the tab shows green for a beat and then swaps.
 */
export function applyFavicon(brand: Brand) {
  const links = document.querySelectorAll<HTMLLinkElement>(
    'link[rel~="icon"], link[rel="apple-touch-icon"]'
  );
  links.forEach((l) => {
    // Anchored on the two known base names rather than "before the first dash
    // or dot" — apple-touch-icon has dashes of its own, and the loose rule
    // turned it into apple-violet-touch-icon.
    const base = l.href.replace("-violet", "");
    l.href = brand === "violet" ? base.replace(/(favicon|apple-touch-icon)/, "$1-violet") : base;
  });
}

const BRAND_KEY = "openimg-brand";

function storedBrand(): Brand {
  try {
    return localStorage.getItem(BRAND_KEY) === "violet" ? "violet" : "green";
  } catch {
    // Private browsing and some embedded webviews throw on localStorage.
    return "green";
  }
}

interface BrandCtx {
  brand: Brand;
  setBrand: (b: Brand) => void;
  toggle: () => void;
}

const Ctx = createContext<BrandCtx | null>(null);

export function BrandProvider({ children }: { children: ReactNode }) {
  const [brand, setBrandState] = useState<Brand>(storedBrand);

  useEffect(() => {
    const root = document.documentElement;
    // Absent for green so the default costs nothing.
    if (brand === "violet") root.setAttribute("data-brand", "violet");
    else root.removeAttribute("data-brand");
    applyFavicon(brand);
  }, [brand]);

  function setBrand(b: Brand) {
    setBrandState(b);
    try {
      localStorage.setItem(BRAND_KEY, b);
    } catch {
      // Non-persistent is acceptable; the in-memory switch still works.
    }
  }

  return (
    <Ctx.Provider
      value={{ brand, setBrand, toggle: () => setBrand(brand === "green" ? "violet" : "green") }}
    >
      {children}
    </Ctx.Provider>
  );
}

export function useBrand() {
  const c = useContext(Ctx);
  if (!c) throw new Error("useBrand 必须在 BrandProvider 内使用");
  return c;
}
